
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  database: dream_development

test:
  <<: *default
  adapter: mysql2
  database: dream_test

production:
  <<: *default
  adapter: postgresql
  database: dream_production
  username: dream
  password: <%= ENV['DREAM_DATABASE_PASSWORD'] %>
